### ISSUE TITLE
Question: How to limit message consumption at a certain RPS?

### ISSUE THREAD

**Issue by IshankGulati** [confluentinc/parallel-consumer#766]
Hi! Thanks for building this lib. We have a use case where we want to limit the message consumption rate at a certain RPS (50K) where the production rate is much higher (400K). The consumption rate is important for us because the downstream service cannot take more load than this. We are using the parallel consumer lib with the Vert.X extension with the following configuration:

Ordering - Key (Though the ordering doesn't matter to us)
Max Concurrency - 800
Batching - Off
Kafka Partitions - 100

Consumer Code:

```
  public void start() {
    var kafkaProperties = new Properties();
    kafkaProperties.put("security.protocol", "SSL");
    kafkaProperties.put("bootstrap.servers", "xyz");
    kafkaProperties.put(
        "key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
    kafkaProperties.put(
        "value.deserializer", "org.apache.kafka.common.serialization.ByteArrayDeserializer");
    kafkaProperties.put("group.id", "abc");
    kafkaProperties.put("enable.auto.commit", false);
    kafkaProperties.put("connections.max.idle.ms", "3600000");
    Consumer<String, byte[]> kafkaConsumer = new KafkaConsumer<>(kafkaProperties)

    var options =
        ParallelConsumerOptions.<String, byte[]>builder()
            .ordering(ProcessingOrder.KEY)
            .maxConcurrency(800)
            .meterRegistry(BackendRegistries.getDefaultNow())
            .consumer(kafkaConsumer)
            .build();
    BackendRegistries.getDefaultNow().config()
        .meterFilter(MeterFilter.ignoreTags("partition"));
    VertxParallelStreamProcessor<String, byte[]> parallelConsumer =
        new VertxParallelEoSStreamProcessor<>(vertx, null, options);

    parallelConsumer.subscribe(Set.of("abc"));

    parallelConsumer.vertxFuture(
        context -> handler.processRecord(context.getSingleConsumerRecord())
            .recover(err -> Future.succeededFuture()));
  }
```

We ran single-node tests with this setup and were able to support 540 RPS (the downstream client that we are calling is slow). When we are running load tests at 400K RPS ingestion rate and 113 consumer nodes, these nodes start consuming a lot more messages than expected and the CPU reaches 100% utilisation which is what we want to avoid. We are also observing that some nodes are taking much more traffic than the other. Could this be because the number of partitions is less than the number of consumer nodes? I can also see consumer poller status fluctuating during the test.
<img width="1250" alt="Screenshot 2024-05-17 at 12 07 43 PM" src="https://github.com/confluentinc/parallel-consumer/assets/10078624/6499fa09-69c1-4fb2-b2db-70b81f4e80e4">

Another observation that we have is that `pc_user_function_processing_time_seconds` is not showing the correct value as the processing time of a message on our end is close to 800ms - 1 sec.
<img width="1249" alt="Screenshot 2024-05-17 at 11 54 09 AM" src="https://github.com/confluentinc/parallel-consumer/assets/10078624/a6aebd0b-39b9-470d-bb7c-0456071c2863">

**Comment by rkolesnev** [comment]
1) 
We are also observing that some nodes are taking much more traffic than the other. Could this be because the number of partitions is less than the number of consumer nodes? 

Yes - consumer node can subscribe to minimum of 1 partition, single partition cannot be split between consumer nodes so with 100 partitions - you can only load maximum of 100 consumer nodes.
You can have less consumer nodes than partitions - then some nodes will have more partitions assigned than others unless it is an even split - i.e. 50 partitions on 20 nodes wont be split evenly, but 50 partitions on 25 nodes - will be split evenly.
In addition actual data distribution between partition can skew load as well.

2)
There is no support for distributed rate limiting in Parallel Consumer - so there is no way to precisely set this behaviour.
But it really depends on what happens when rate is exceeded in downstream service - is it just slowing down? is it returning error like quota exceeded etc?
Parallel Consumer can retry messages indefinitely if needed - and it uses back-pressure logic to slow down consumption from Kafka topic(s) when downstream processing is slower than consumption - so generally it should not be needed to rate limit read from Kafka in Parallel Consumer.

If downstream service is not handling high load well - for example overloading it may cause it to crash etc - you could either add rate limiting to the downstream service - so that it returns error back to Parallel Consumer when certain load / RequestsPerSecond threshold is exceeded and let ParallelConsumer delay the messages through retry logic / kick in back-pressure.
Or if down stream service is outside of your control - add intermediate circuit breaker service with such a rate limiting logic between Parallel Consumer and the downstream service. 
You can probably implement some sort of shared request counter / monitor in the user function using something like Redis / other cache shared across all instances of ParallelConsumer - basically implementing your own distributed rate limiting directly in ParallelConsumer code - but utilizing intermediate rate limiter service might be easier as there should be out of box services ...

**Comment by rkolesnev** [comment]
regarding metrics - they are implemented in the normal thread based ParallelConsumer implementation - for Vert.x / Reactor - they may be incomplete / inaccurate.

**Comment by rkolesnev** [comment]
In scenario when ParallelConsumer consumes messages from Kafka faster than it can process them - once the internal queue is filled - it will start pausing / resuming KafkaConsumer as needed to maintain the queue filled but not poll more messages until queue size drops under the max size - hence applying back-pressure to the consumption side. 
It should manifest in the rate of consumption dropping and BrokerPoller status changing to Paused intermittently.
